---
kind: pipeline
type: docker
name: deploy development

clone:
  depth: 1

steps:
  - name: Build and Deploy
    image: plugins/ansible:3
    settings:
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventories/dev/hosts
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - development
  event:
    - push

---
kind: pipeline
type: docker
name: deploy certification

clone:
  depth: 1

steps:
  - name: Build and Deploy
    image: plugins/ansible:3
    settings:
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventories/cert/hosts
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password

trigger:
  branch:
    - stable
  event:
    - push

---
kind: pipeline
type: docker
name: deploy production

clone:
  depth: 1

steps:
  - name: Build and Deploy
    image: plugins/ansible:3
    settings:
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventories/prod/hosts
      private_key:
        from_secret: ansible_private_key
      vault_password:
        from_secret: ansible_vault_password

trigger:
  event:
    - tag
...
