# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/master_id

- hosts: all
  strategy: free

  tasks:

    - name: 'Ensure existence of configuration directory: {{ directories_files }}/certs'
      command: mkdir -p {{ directories_files }}/certs

    - name: Render public certificates
      ansible.builtin.copy:
        content: '{{ item.cert }}'
        dest: '{{ directories_files }}/certs/{{ item.common_name }}.cert'
      with_items: '{{ certs }}'
      loop_control:
        label: "{{ item.common_name }}.cert"
      when: certs is defined

    - name: Render private keys
      ansible.builtin.copy:
        content: '{{ item.key }}'
        dest: '{{ directories_files }}/certs/{{ item.common_name }}.key'
      with_items: '{{ certs }}'
      loop_control:
        label: "{{ item.common_name }}.key"
      when: certs is defined

    - name: 'Render dynamic configuration to {{ app_data }}/traefik.yaml'
      template:
        src: traefik.yaml.j2
        dest: "{{ directories_files }}/traefik.yaml"
      become: yes
      become_user: "{{ user }}"

    - name: Render docker-compose.yaml & deploy stack
      import_role:
        name: docker-deploy
      vars:
        with_registry: no
