# ansible-playbook deploy.yaml -i inventories/dev/hosts --vault-id ~/.tokens/master_id

- hosts: all
  strategy: free

  tasks:


    - name: "Ensuring existence of configuration directory: {{ app_data }}"
      file:
        state: directory
        path: '{{ app_data }}'

    - name: "Rendering docker-compose.yaml file"
      template:
        src: "docker-compose.yaml.j2"
        dest: "{{ app_data }}/docker-compose.yaml"
      
    - name: "Running `Docker stack deploy`"
      shell: >
        docker stack deploy 
        --with-registry-auth 
        --prune 
        -c {{ app_data }}/docker-compose.yaml 
        {{ docker_stack }}
