# ansible-playbook .ansible/deploy.yaml -i .ansible/inventory/development/hosts --vault-id ~/.tokens/master_id --extra-vars 'git_repository=traefik git_branch=development'

- hosts: all
  strategy: free

  tasks:

    - name: 'Ensure existence of configuration directory: {{ directories_files }}/dynamic'
      command: mkdir -p {{ directories_files }}/dynamic

    - name: 'Ensure existence of configuration directory: {{ directories_files }}/acme'
      command: mkdir -p {{ directories_files }}/acme

    - name: 'Ensure existence of configuration directory: {{ directories_files }}/certs'
      command: mkdir -p {{ directories_files }}/certs

    - name: Render public certificates
      ansible.builtin.copy:
        content: '{{ item.crt }}'
        dest: '{{ directories_files }}/certs/{{ item.common_name }}.crt'
      with_items: '{{ certs }}'
      loop_control:
        label: "{{ item.common_name }}.crt"
      when: certs is defined

    - name: Render private keys
      ansible.builtin.copy:
        content: '{{ item.key }}'
        dest: '{{ directories_files }}/certs/{{ item.common_name }}.key'
      with_items: '{{ certs }}'
      loop_control:
        label: "{{ item.common_name }}.key"
      when: certs is defined

    - name: 'Render dynamic configuration to {{ directories_files }}/dynamic/traefik.yaml'
      template:
        src: traefik.yaml.j2
        dest: "{{ directories_files }}/dynamic/traefik.yaml"

    - import_role:
        name: docker_deploy

    - name: Allow port 80 (HTTP)
      ufw:
        rule: allow
        port: '80'
        proto: any
      become: yes

    - name: Allow port 443 (HTTPS)
      ufw:
        rule: allow
        port: '443'
        proto: any
      become: yes

    - name: Reload Firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes
