# ansible-playbook .ansible/deploy.yaml -i .ansible/inventory/development/hosts --vault-id ~/.tokens/master_id --extra-vars 'git_repository=traefik git_branch=development'

- hosts: all
  strategy: free
  roles: 
    - common

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - include_role:
        name: common
        tasks_from: make_data_dir

    - name: Ensure directories exists
      file: 
        path: '{{ directory }}'
        state: directory
      loop_control:
        loop_var: directory
      loop:
        - '{{ config_dir }}/dynamic'
        - '{{ config_dir }}/certs'
        - '{{ data_dir }}/acme'

    - name: Render public certificates
      copy:
        content: '{{ item.crt }}'
        dest: '{{ config_dir }}/certs/{{ item.common_name }}.crt'
      with_items: '{{ certs }}'
      loop_control:
        label: "{{ item.common_name }}.crt"
      when: certs is defined

    - name: Render private keys
      copy:
        content: '{{ item.key }}'
        dest: '{{ config_dir }}/certs/{{ item.common_name }}.key'
      with_items: '{{ certs }}'
      loop_control:
        label: "{{ item.common_name }}.key"
      when: certs is defined

    - name: 'Render dynamic configuration to {{ config_dir }}/dynamic/traefik.yaml'
      template:
        src: traefik.yaml.j2
        dest: "{{ config_dir }}/dynamic/traefik.yaml"

    - include_role:
        name: docker
        tasks_from: stack_deploy

    - name: Allow port 80 (HTTP)
      ufw:
        rule: allow
        port: '80'
        proto: any
      become: yes

    - name: Allow port 443 (HTTPS)
      ufw:
        rule: allow
        port: '443'
        proto: any
      become: yes

    - name: Reload Firewall and enable at boot
      ufw:
        state: enabled
        policy: deny
      become: yes
